DEFAULTS = {
    "api_compat": "openai",
    "base_url": "https://api.x.ai/v1",
    "api_key_env": "GROK_API_KEY",
    "model": "grok-4",
    "sub_agent_model": "grok-4",
    "insight_model": "grok-4",
    "inline_model": "grok-4-mini",
    "planner_model": "grok-4",
    "web_search_provider": "grok",
    "vision_provider": "grok",
    "thinking_model": "high",
    "thinking_sub_agent": "low",
    "thinking_insight": "low",
    "rate_limit_interval": 0,
}
