DEFAULTS = {
    "api_compat": "openai",
    "base_url": "https://api.deepseek.com",
    "api_key_env": "DEEPSEEK_API_KEY",
    "model": "deepseek-chat",
    "sub_agent_model": "deepseek-chat",
    "insight_model": "deepseek-chat",
    "inline_model": "deepseek-chat",
    "planner_model": "deepseek-chat",
    "web_search_provider": None,
    "vision_provider": None,
    "thinking_model": "default",
    "thinking_sub_agent": "default",
    "thinking_insight": "default",
    "rate_limit_interval": 0,
}
