DEFAULTS = {
    "api_compat": "openai",
    "base_url": None,
    "api_key_env": "CUSTOM_API_KEY",
    "model": "",
    "sub_agent_model": "",
    "insight_model": "",
    "inline_model": "",
    "planner_model": "",
    "fallback_model": "",
    "web_search_provider": None,
    "vision_provider": None,
    "thinking_model": "default",
    "thinking_sub_agent": "default",
    "thinking_insight": "default",
    "rate_limit_interval": 0,
}
