"""
Script generator — produces self-contained Python scripts from SavedPipeline data.

Given a ``SavedPipeline.to_dict()`` output, generates executable Python scripts
that reproduce the entire pipeline (fetch → transform → render) without any
xhelio imports.  The output is a dict mapping filenames to content strings:

- ``pipeline.py`` — always present, contains fetch/transform/render/run + CLI
- ``component.tsx`` — present only for JSX backend (the React component)

Usage::

    from data_ops.script_gen import generate_script

    pipeline = SavedPipeline.from_dict(data)
    files = generate_script(pipeline.to_dict())
    for filename, content in files.items():
        Path(filename).write_text(content)
"""

from __future__ import annotations

from datetime import datetime, timezone

from data_ops.pipeline import topological_sort_steps
from rendering.registry import RENDER_TOOL_NAMES


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_script(pipeline_data: dict) -> dict[str, str]:
    """Generate self-contained Python script(s) from a saved pipeline dict.

    Args:
        pipeline_data: Output of ``SavedPipeline.to_dict()``.

    Returns:
        Dict mapping filename to file content.  Always includes
        ``"pipeline.py"``.  May include ``"component.tsx"`` for JSX backend.

    Raises:
        ValueError: If pipeline has no steps.
    """
    steps = pipeline_data.get("steps", [])
    if not steps:
        raise ValueError("Pipeline has no steps")

    sorted_steps = topological_sort_steps(steps)

    # Classify steps
    fetch_steps = [s for s in sorted_steps if s["tool"] == "fetch_data"]
    transform_steps = [
        s for s in sorted_steps
        if s["tool"] == "run_code"
    ]
    render_steps = [
        s for s in sorted_steps
        if s["tool"] in RENDER_TOOL_NAMES
    ]

    # Detect backend
    backend = _detect_backend(render_steps)

    # Build sections
    header = _build_header(pipeline_data, fetch_steps, backend)
    imports = _build_imports(fetch_steps, backend)
    fetch_fn = _build_fetch_function(fetch_steps)
    transform_fn = _build_transform_function(transform_steps, sorted_steps)
    render_fn = _build_render_function(render_steps, backend)
    run_fn = _build_run_function(bool(transform_steps), backend)
    main_block = _build_main_block(pipeline_data, backend)

    parts = [header, imports, fetch_fn]
    if transform_fn:
        parts.append(transform_fn)
    parts.extend([render_fn, run_fn, main_block])

    script = "\n\n".join(parts) + "\n"

    result: dict[str, str] = {"pipeline.py": script}

    # JSX: extract component code
    if backend == "jsx":
        for s in render_steps:
            code = s["params"].get("code", "")
            if code:
                result["component.tsx"] = code

    return result


# ---------------------------------------------------------------------------
# Backend detection
# ---------------------------------------------------------------------------

def _detect_backend(render_steps: list[dict]) -> str:
    """Return 'plotly', 'mpl', 'jsx', or 'none'."""
    for s in render_steps:
        tool = s["tool"]
        if tool == "render_plotly_json":
            return "plotly"
        elif tool == "generate_mpl_script":
            return "mpl"
        elif tool == "generate_jsx_component":
            return "jsx"
    return "none"


# ---------------------------------------------------------------------------
# Header / docstring
# ---------------------------------------------------------------------------

def _build_header(pipeline_data: dict, fetch_steps: list[dict],
                  backend: str) -> str:
    name = pipeline_data.get("name", "Untitled Pipeline").replace('"""', "'''")
    tr = pipeline_data.get("time_range_original", ["", ""])
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Requirements
    reqs = ["numpy", "pandas"]
    has_cdaweb = any(not _is_ppi(s) for s in fetch_steps)
    has_ppi = any(_is_ppi(s) for s in fetch_steps)
    if has_cdaweb:
        reqs.append("cdasws")
    if has_ppi:
        reqs.append("requests")
    if backend == "plotly":
        reqs.append("plotly")
    elif backend == "mpl":
        reqs.append("matplotlib")

    reqs_str = "pip install " + " ".join(reqs)

    lines = [
        '"""',
        name,
        f"Generated by xhelio on {date_str}",
    ]
    if tr[0] or tr[1]:
        lines.append(f"Original time range: {tr[0]} to {tr[1]}")
    lines.append("")
    lines.append(f"Requirements: {reqs_str}")
    lines.append('"""')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------

def _build_imports(fetch_steps: list[dict], backend: str) -> str:
    lines = [
        "import argparse",
        "from datetime import datetime",
        "import numpy as np",
        "import pandas as pd",
    ]
    has_cdaweb = any(not _is_ppi(s) for s in fetch_steps)
    has_ppi = any(_is_ppi(s) for s in fetch_steps)
    if has_cdaweb:
        lines.append("from cdasws import CdasWs")
    if has_ppi:
        lines.append("import requests")
    if backend == "plotly":
        lines.append("import plotly.graph_objects as go")
    elif backend == "mpl":
        lines.append("import matplotlib.pyplot as plt")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Fetch function
# ---------------------------------------------------------------------------

def _is_ppi(step: dict) -> bool:
    """Return True if fetch step targets a PPI dataset."""
    ds = step.get("params", {}).get("dataset_id", "")
    return ds.startswith("urn:nasa:pds:") or ds.startswith("pds3:")


def _build_fetch_function(fetch_steps: list[dict]) -> str:
    has_cdaweb = any(not _is_ppi(s) for s in fetch_steps)
    lines = [
        'def fetch_data(start: str, end: str) -> dict[str, pd.DataFrame]:',
        '    """Fetch all required datasets."""',
        '    data = {}',
        '    start_dt = datetime.fromisoformat(start)',
        '    end_dt = datetime.fromisoformat(end)',
    ]
    if has_cdaweb:
        lines.append('    cdas = CdasWs()')

    for step in fetch_steps:
        params = step["params"]
        ds_id = params.get("dataset_id", "UNKNOWN")
        param_id = params.get("parameter_id", "UNKNOWN")
        label = step.get("output_label", ds_id)

        lines.append("")
        lines.append(f"    # {step.get('description', 'Fetch data')}")

        if _is_ppi(step):
            lines.append(f"    # PPI dataset: {ds_id} / {param_id}")
            lines.append(f"    # Fetch from PDS Planetary Plasma Interactions archive")
            lines.append(f"    raise NotImplementedError(")
            lines.append(f"        \"PPI fetch for '{ds_id}' requires archive-specific URL. \"")
            lines.append(f"        \"See https://pds-ppi.igpp.ucla.edu/ for data access.\"")
            lines.append(f"    )")
            lines.append(f"    # data[\"{label}\"] = <parsed DataFrame>")
        else:
            lines.append(f"    status, xr_data = cdas.get_data(")
            lines.append(f"        \"{ds_id}\",")
            lines.append(f"        [\"{param_id}\"],")
            lines.append(f"        start_dt,")
            lines.append(f"        end_dt,")
            lines.append(f"    )")
            lines.append(f"    data[\"{label}\"] = xr_data.to_dataframe()")

    lines.append("")
    lines.append("    return data")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Transform function
# ---------------------------------------------------------------------------

def _build_transform_function(transform_steps: list[dict],
                              all_steps: list[dict]) -> str | None:
    """Build the transform() function.  Returns None if no transforms."""
    if not transform_steps:
        return None

    # Build step_id → step lookup for resolving input labels
    step_by_id = {s["step_id"]: s for s in all_steps}

    lines = [
        'def transform(data: dict[str, pd.DataFrame]) -> dict[str, pd.DataFrame]:',
        '    """Apply all data transformations."""',
    ]

    for step in transform_steps:
        tool = step["tool"]
        params = step["params"]
        code = params.get("code", "")
        output_label = step.get("output_label", "result")
        desc = step.get("description", tool)

        lines.append("")
        lines.append(f"    # {desc}")

        if tool == "run_code":
            # Resolve input label
            input_ids = step.get("inputs", [])
            if input_ids:
                input_step = step_by_id.get(input_ids[0])
                if input_step:
                    input_label = input_step.get("output_label", "")
                    lines.append(f"    df = data[\"{input_label}\"]")
                else:
                    lines.append(f"    df = data[\"{input_ids[0]}\"]")
            else:
                lines.append(f"    # No input specified")

            # Inline the code
            for code_line in code.splitlines():
                lines.append(f"    {code_line}")

            # Store result
            lines.append(f"    if isinstance(result, pd.Series):")
            lines.append(f"        result = result.to_frame()")
            lines.append(f"    data[\"{output_label}\"] = result")

    lines.append("")
    lines.append("    return data")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Render function
# ---------------------------------------------------------------------------

def _build_render_function(render_steps: list[dict], backend: str) -> str:
    if backend == "plotly":
        return _build_plotly_render(render_steps)
    elif backend == "mpl":
        return _build_mpl_render(render_steps)
    elif backend == "jsx":
        return _build_jsx_render(render_steps)
    else:
        return _build_noop_render()


def _build_plotly_render(render_steps: list[dict]) -> str:
    lines = [
        'def render(data: dict[str, pd.DataFrame]):',
        '    """Create the Plotly visualization."""',
        '    traces = []',
    ]

    for step in render_steps:
        fig_json = step["params"].get("figure_json", {})
        traces_json = fig_json.get("data", [])
        layout_json = fig_json.get("layout", {})

        for i, trace in enumerate(traces_json):
            data_label = trace.get("data_label")
            # Build a clean trace dict without data_label
            clean_trace = {k: v for k, v in trace.items() if k != "data_label"}

            if data_label:
                lines.append("")
                lines.append(f"    # Trace from data label: {data_label}")
                lines.append(f"    df_{i} = data[\"{data_label}\"]")
                lines.append(f"    trace_{i} = {_dict_repr(clean_trace)}")
                lines.append(f"    trace_{i}[\"x\"] = df_{i}.index")
                lines.append(f"    if df_{i}.shape[1] == 1:")
                lines.append(f"        trace_{i}[\"y\"] = df_{i}.iloc[:, 0]")
                lines.append(f"    else:")
                lines.append(f"        trace_{i}[\"y\"] = df_{i}.values")
                lines.append(f"    traces.append(go.Scatter(**trace_{i}))")
            else:
                lines.append(f"    traces.append(go.Scatter(**{_dict_repr(clean_trace)}))")

        # Layout
        lines.append("")
        lines.append(f"    layout = {_dict_repr(layout_json)}")
        lines.append(f"    fig = go.Figure(data=traces, layout=layout)")
        lines.append(f"    return fig")

    return "\n".join(lines)


def _build_mpl_render(render_steps: list[dict]) -> str:
    lines = [
        'def render(data: dict[str, pd.DataFrame]):',
        '    """Create the matplotlib visualization."""',
    ]

    for step in render_steps:
        code = step["params"].get("code", "")
        for code_line in code.splitlines():
            lines.append(f"    {code_line}")

    lines.append("")
    lines.append("    return fig")
    return "\n".join(lines)


def _build_jsx_render(render_steps: list[dict]) -> str:
    lines = [
        'def render(data: dict[str, pd.DataFrame]):',
        '    """Export data as CSV files for the JSX component."""',
        '    paths = []',
        '    for label, df in data.items():',
        '        path = f"{label}.csv"',
        '        df.to_csv(path)',
        '        paths.append(path)',
        '    return paths',
    ]
    return "\n".join(lines)


def _build_noop_render() -> str:
    return (
        'def render(data: dict[str, pd.DataFrame]):\n'
        '    """No visualization backend detected."""\n'
        '    return data'
    )


# ---------------------------------------------------------------------------
# run() function
# ---------------------------------------------------------------------------

def _build_run_function(has_transforms: bool, backend: str) -> str:
    lines = [
        'def run(start: str, end: str):',
        '    """Full pipeline: fetch -> transform -> render."""',
        '    data = fetch_data(start, end)',
    ]
    if has_transforms:
        lines.append('    data = transform(data)')
    lines.append('    return render(data)')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# __main__ block
# ---------------------------------------------------------------------------

def _build_main_block(pipeline_data: dict, backend: str) -> str:
    name = pipeline_data.get("name", "Pipeline").replace('"', '\\"')
    lines = [
        'if __name__ == "__main__":',
        f'    parser = argparse.ArgumentParser(description="{name}")',
        '    parser.add_argument("--start", required=True, help="Start time (YYYY-MM-DD or ISO 8601)")',
        '    parser.add_argument("--end", required=True, help="End time (YYYY-MM-DD or ISO 8601)")',
        '    args = parser.parse_args()',
        '    result = run(args.start, args.end)',
    ]
    if backend == "plotly":
        lines.append('    result.show()')
    elif backend == "mpl":
        lines.append('    plt.show()')
    elif backend == "jsx":
        lines.append('    print("Exported CSV files:", result)')
    else:
        lines.append('    print("Done:", result)')
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dict_repr(d: dict) -> str:
    """Return a readable repr of a dict suitable for generated Python code.

    Uses ``repr()`` instead of ``json.dumps()`` so that booleans (True/False)
    and None are valid Python literals rather than JSON's true/false/null.
    """
    return repr(d)
